/* chvalid battery slice — GENERATED by tests/libxml2/gen_chvalid_battery.py.
 * DO NOT EDIT. Regenerate all slices:
 *   tests/libxml2/gen_chvalid_battery.py <libxml2>/codegen/ranges.inc \
 *       --out-dir tests/libxml2/battery
 * Arc-5 S3 differential battery over libxml2 chvalid.c; see the
 * generator's docstring for the point-set construction.
 */
#include <libxml/chvalid.h>
#include <stdio.h>

#define BATTERY_N 50u

static const unsigned int points[50] = {
    0xbe7u, 0xbe8u, 0xbeeu, 0xbefu, 0xbf0u, 0xc00u, 0xc01u, 0xc02u, 
    0xc03u, 0xc04u, 0xc05u, 0xc06u, 0xc0bu, 0xc0cu, 0xc0du, 0xc0eu, 
    0xc0fu, 0xc10u, 0xc11u, 0xc12u, 0xc13u, 0xc27u, 0xc28u, 0xc29u, 
    0xc2au, 0xc2bu, 0xc32u, 0xc33u, 0xc34u, 0xc35u, 0xc36u, 0xc38u, 
    0xc39u, 0xc3au, 0xc3du, 0xc3eu, 0xc3fu, 0xc43u, 0xc44u, 0xc45u, 
    0xc46u, 0xc47u, 0xc48u, 0xc49u, 0xc4au, 0xc4bu, 0xc4cu, 0xc4du, 
    0xc4eu, 0xc54u
};

int main(void) {
    unsigned int h = 5381u;
    unsigned int i;
    for (i = 0u; i < BATTERY_N; i++) {
        unsigned int c = points[i];
        unsigned int bits = 0u;
        /* exported functions: cross-TU calls into chvalid.c */
        bits = (bits << 1) | (unsigned int)(xmlIsBaseChar(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsBlank(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsChar(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsCombining(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsDigit(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsExtender(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsIdeographic(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsPubidChar(c) != 0);
        /* group macros expanded in THIS TU (libxml/chvalid.h) */
        bits = (bits << 1) | (unsigned int)(xmlIsBaseCharQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsBlankQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsCharQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsCombiningQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsDigitQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsExtenderQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsIdeographicQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsPubidCharQ(c) != 0);
        /* direct xmlCharInRange over each exported range group */
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsBaseCharGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsCharGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsCombiningGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsDigitGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsExtenderGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsIdeographicGroup) != 0);
        h = h * 33u + bits;   /* unsigned wrap-around: defined */
    }
    printf("chvalid_battery n=%u h=%u\n", (unsigned int)BATTERY_N, h);
    return (int)(h % 1000000007u);
}
