/* chvalid battery slice — GENERATED by tests/libxml2/gen_chvalid_battery.py.
 * DO NOT EDIT. Regenerate all slices:
 *   tests/libxml2/gen_chvalid_battery.py <libxml2>/codegen/ranges.inc \
 *       --out-dir tests/libxml2/battery
 * Arc-5 S3 differential battery over libxml2 chvalid.c; see the
 * generator's docstring for the point-set construction.
 */
#include <libxml/chvalid.h>
#include <stdio.h>

#define BATTERY_N 50u

static const unsigned int points[50] = {
    0xd44u, 0xd45u, 0xd46u, 0xd47u, 0xd48u, 0xd49u, 0xd4au, 0xd4bu, 
    0xd4cu, 0xd4du, 0xd4eu, 0xd56u, 0xd57u, 0xd58u, 0xd5fu, 0xd60u, 
    0xd61u, 0xd62u, 0xd65u, 0xd66u, 0xd67u, 0xd6eu, 0xd6fu, 0xd70u, 
    0xe00u, 0xe01u, 0xe02u, 0xe2du, 0xe2eu, 0xe2fu, 0xe30u, 0xe31u, 
    0xe32u, 0xe33u, 0xe34u, 0xe35u, 0xe39u, 0xe3au, 0xe3bu, 0xe3fu, 
    0xe40u, 0xe41u, 0xe44u, 0xe45u, 0xe46u, 0xe47u, 0xe48u, 0xe4du, 
    0xe4eu, 0xe4fu
};

int main(void) {
    unsigned int h = 5381u;
    unsigned int i;
    for (i = 0u; i < BATTERY_N; i++) {
        unsigned int c = points[i];
        unsigned int bits = 0u;
        /* exported functions: cross-TU calls into chvalid.c */
        bits = (bits << 1) | (unsigned int)(xmlIsBaseChar(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsBlank(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsChar(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsCombining(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsDigit(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsExtender(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsIdeographic(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsPubidChar(c) != 0);
        /* group macros expanded in THIS TU (libxml/chvalid.h) */
        bits = (bits << 1) | (unsigned int)(xmlIsBaseCharQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsBlankQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsCharQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsCombiningQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsDigitQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsExtenderQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsIdeographicQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsPubidCharQ(c) != 0);
        /* direct xmlCharInRange over each exported range group */
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsBaseCharGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsCharGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsCombiningGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsDigitGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsExtenderGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsIdeographicGroup) != 0);
        h = h * 33u + bits;   /* unsigned wrap-around: defined */
    }
    printf("chvalid_battery n=%u h=%u\n", (unsigned int)BATTERY_N, h);
    return (int)(h % 1000000007u);
}
