/* chvalid battery slice — GENERATED by tests/libxml2/gen_chvalid_battery.py.
 * DO NOT EDIT. Regenerate all slices:
 *   tests/libxml2/gen_chvalid_battery.py <libxml2>/codegen/ranges.inc \
 *       --out-dir tests/libxml2/battery
 * Arc-5 S3 differential battery over libxml2 chvalid.c; see the
 * generator's docstring for the point-set construction.
 */
#include <libxml/chvalid.h>
#include <stdio.h>

#define BATTERY_N 50u

static const unsigned int points[50] = {
    0x6ddu, 0x6deu, 0x6dfu, 0x6e0u, 0x6e1u, 0x6e3u, 0x6e4u, 0x6e5u, 
    0x6e6u, 0x6e7u, 0x6e8u, 0x6e9u, 0x6eau, 0x6ebu, 0x6ecu, 0x6edu, 
    0x6eeu, 0x6efu, 0x6f0u, 0x6f1u, 0x6f8u, 0x6f9u, 0x6fau, 0x900u, 
    0x901u, 0x902u, 0x903u, 0x904u, 0x905u, 0x906u, 0x938u, 0x939u, 
    0x93au, 0x93bu, 0x93cu, 0x93du, 0x93eu, 0x93fu, 0x94bu, 0x94cu, 
    0x94du, 0x94eu, 0x950u, 0x951u, 0x952u, 0x953u, 0x954u, 0x955u, 
    0x957u, 0x958u
};

int main(void) {
    unsigned int h = 5381u;
    unsigned int i;
    for (i = 0u; i < BATTERY_N; i++) {
        unsigned int c = points[i];
        unsigned int bits = 0u;
        /* exported functions: cross-TU calls into chvalid.c */
        bits = (bits << 1) | (unsigned int)(xmlIsBaseChar(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsBlank(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsChar(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsCombining(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsDigit(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsExtender(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsIdeographic(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsPubidChar(c) != 0);
        /* group macros expanded in THIS TU (libxml/chvalid.h) */
        bits = (bits << 1) | (unsigned int)(xmlIsBaseCharQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsBlankQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsCharQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsCombiningQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsDigitQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsExtenderQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsIdeographicQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsPubidCharQ(c) != 0);
        /* direct xmlCharInRange over each exported range group */
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsBaseCharGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsCharGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsCombiningGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsDigitGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsExtenderGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsIdeographicGroup) != 0);
        h = h * 33u + bits;   /* unsigned wrap-around: defined */
    }
    printf("chvalid_battery n=%u h=%u\n", (unsigned int)BATTERY_N, h);
    return (int)(h % 1000000007u);
}
