/* chvalid battery slice — GENERATED by tests/libxml2/gen_chvalid_battery.py.
 * DO NOT EDIT. Regenerate all slices:
 *   tests/libxml2/gen_chvalid_battery.py <libxml2>/codegen/ranges.inc \
 *       --out-dir tests/libxml2/battery
 * Arc-5 S3 differential battery over libxml2 chvalid.c; see the
 * generator's docstring for the point-set construction.
 */
#include <libxml/chvalid.h>
#include <stdio.h>

#define BATTERY_N 50u

static const unsigned int points[50] = {
    0x141u, 0x142u, 0x147u, 0x148u, 0x149u, 0x14au, 0x14bu, 0x17du, 
    0x17eu, 0x17fu, 0x180u, 0x181u, 0x1c2u, 0x1c3u, 0x1c4u, 0x1ccu, 
    0x1cdu, 0x1ceu, 0x1efu, 0x1f0u, 0x1f1u, 0x1f3u, 0x1f4u, 0x1f5u, 
    0x1f6u, 0x1f9u, 0x1fau, 0x1fbu, 0x216u, 0x217u, 0x218u, 0x24fu, 
    0x250u, 0x251u, 0x2a7u, 0x2a8u, 0x2a9u, 0x2bau, 0x2bbu, 0x2bcu, 
    0x2c0u, 0x2c1u, 0x2c2u, 0x2cfu, 0x2d0u, 0x2d1u, 0x2d2u, 0x2ffu, 
    0x300u, 0x301u
};

int main(void) {
    unsigned int h = 5381u;
    unsigned int i;
    for (i = 0u; i < BATTERY_N; i++) {
        unsigned int c = points[i];
        unsigned int bits = 0u;
        /* exported functions: cross-TU calls into chvalid.c */
        bits = (bits << 1) | (unsigned int)(xmlIsBaseChar(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsBlank(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsChar(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsCombining(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsDigit(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsExtender(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsIdeographic(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsPubidChar(c) != 0);
        /* group macros expanded in THIS TU (libxml/chvalid.h) */
        bits = (bits << 1) | (unsigned int)(xmlIsBaseCharQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsBlankQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsCharQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsCombiningQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsDigitQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsExtenderQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsIdeographicQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsPubidCharQ(c) != 0);
        /* direct xmlCharInRange over each exported range group */
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsBaseCharGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsCharGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsCombiningGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsDigitGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsExtenderGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsIdeographicGroup) != 0);
        h = h * 33u + bits;   /* unsigned wrap-around: defined */
    }
    printf("chvalid_battery n=%u h=%u\n", (unsigned int)BATTERY_N, h);
    return (int)(h % 1000000007u);
}
