/* chvalid battery slice — GENERATED by tests/libxml2/gen_chvalid_battery.py.
 * DO NOT EDIT. Regenerate all slices:
 *   tests/libxml2/gen_chvalid_battery.py <libxml2>/codegen/ranges.inc \
 *       --out-dir tests/libxml2/battery
 * Arc-5 S3 differential battery over libxml2 chvalid.c; see the
 * generator's docstring for the point-set construction.
 */
#include <libxml/chvalid.h>
#include <stdio.h>

#define BATTERY_N 50u

static const unsigned int points[50] = {
    0x40du, 0x40eu, 0x40fu, 0x44eu, 0x44fu, 0x450u, 0x451u, 0x452u, 
    0x45bu, 0x45cu, 0x45du, 0x45eu, 0x45fu, 0x480u, 0x481u, 0x482u, 
    0x483u, 0x484u, 0x485u, 0x486u, 0x487u, 0x48fu, 0x490u, 0x491u, 
    0x4c3u, 0x4c4u, 0x4c5u, 0x4c6u, 0x4c7u, 0x4c8u, 0x4c9u, 0x4cau, 
    0x4cbu, 0x4ccu, 0x4cdu, 0x4cfu, 0x4d0u, 0x4d1u, 0x4eau, 0x4ebu, 
    0x4ecu, 0x4edu, 0x4eeu, 0x4efu, 0x4f4u, 0x4f5u, 0x4f6u, 0x4f7u, 
    0x4f8u, 0x4f9u
};

int main(void) {
    unsigned int h = 5381u;
    unsigned int i;
    for (i = 0u; i < BATTERY_N; i++) {
        unsigned int c = points[i];
        unsigned int bits = 0u;
        /* exported functions: cross-TU calls into chvalid.c */
        bits = (bits << 1) | (unsigned int)(xmlIsBaseChar(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsBlank(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsChar(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsCombining(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsDigit(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsExtender(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsIdeographic(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsPubidChar(c) != 0);
        /* group macros expanded in THIS TU (libxml/chvalid.h) */
        bits = (bits << 1) | (unsigned int)(xmlIsBaseCharQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsBlankQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsCharQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsCombiningQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsDigitQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsExtenderQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsIdeographicQ(c) != 0);
        bits = (bits << 1) | (unsigned int)(xmlIsPubidCharQ(c) != 0);
        /* direct xmlCharInRange over each exported range group */
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsBaseCharGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsCharGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsCombiningGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsDigitGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsExtenderGroup) != 0);
        bits = (bits << 1) | (unsigned int)(xmlCharInRange(c, &xmlIsIdeographicGroup) != 0);
        h = h * 33u + bits;   /* unsigned wrap-around: defined */
    }
    printf("chvalid_battery n=%u h=%u\n", (unsigned int)BATTERY_N, h);
    return (int)(h % 1000000007u);
}
