/* SpecLab linked-list harness (IntList_append Form 1, WRONG-LINK PLANT).
   Generated by SpecLab.mkHarness — do not edit by hand.
   Idiom lineage: golean three-phase harness (setup - call - test);
   see lean_frontend/speclab/README.md. */

void *malloc(unsigned long size);
void free(void *p);

/* TARGET — PLANT VARIANT (template-note §plant-test): IntList_append
   is deliberately BROKEN (wrong link: xs->tail = ys skips the
   recursion's result, orphaning every deeper xs node). A
   healthy-looking verdict from this program on xs.length >= 2 means
   the harness is vacuous — and the orphaned nodes are the leak
   observable's red witness. */

struct int_list {
  int head;
  struct int_list* tail;
};

struct int_list* IntList_append(struct int_list* xs, struct int_list* ys)
{
  if (xs == 0) {
    return ys;
  } else {
    struct int_list *new_tail = IntList_append(xs->tail, ys);
    xs->tail = ys; /* PLANT: wrong link (new_tail dropped) */
    return xs;
  }
}

int main(void)
{
  const unsigned char choices[] = { 2, 0, 1, 2, 3, 4, 5, 6, 7, 8, 1, 0, 9, 10, 11, 12 };
  const unsigned char expected[] = { 3, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 };
  struct int_list *xs;
  struct int_list *ys;
  struct int_list *r;
  struct int_list *p;
  struct int_list *t;
  struct int_list **link;
  unsigned char out[68]; /* max obs: append 2+4*16=66; build-only 4+4*16=68 */
  unsigned long i, j, m, n1, n2, off, obs;
  long v;
  /* phase 0 — stream validity (total on any splice):
     u16le(n1) ++ n1 x i32le ++ u16le(n2) ++ n2 x i32le; caps 8/8 */
  if (sizeof(choices) < 2u) { return 254; }
  n1 = (unsigned long)choices[0] + 256u * (unsigned long)choices[1];
  if (n1 > 8u) { return 254; }
  if (sizeof(choices) < 4u + 4u * n1) { return 254; }
  n2 = (unsigned long)choices[2u + 4u * n1]
     + 256u * (unsigned long)choices[3u + 4u * n1];
  if (n2 > 8u) { return 254; }
  if (sizeof(choices) != 4u + 4u * n1 + 4u * n2) { return 254; }
  /* phase 1 — BUILDER (idiom fragment): stream-driven list
     constructor — node-by-node malloc, tail-link threading, i32le
     element codec, two's-complement into int (UB-free) */
  xs = 0; link = &xs;
  for (i = 0u; i < n1; i++) {
    p = (struct int_list*)malloc(sizeof(struct int_list));
    if (p == 0) { return 252; }
    off = 2u + 4u * i;
    v = (long)((unsigned long)choices[off]
        + 256u * (unsigned long)choices[off + 1u]
        + 65536u * (unsigned long)choices[off + 2u]
        + 16777216u * (unsigned long)choices[off + 3u]);
    if (v >= 2147483648L) { v = v - 4294967296L; }
    p->head = (int)v;
    p->tail = 0;
    *link = p; link = &p->tail;
  }
  ys = 0; link = &ys;
  for (i = 0u; i < n2; i++) {
    p = (struct int_list*)malloc(sizeof(struct int_list));
    if (p == 0) { return 252; }
    off = 4u + 4u * n1 + 4u * i;
    v = (long)((unsigned long)choices[off]
        + 256u * (unsigned long)choices[off + 1u]
        + 65536u * (unsigned long)choices[off + 2u]
        + 16777216u * (unsigned long)choices[off + 3u]);
    if (v >= 2147483648L) { v = v - 4294967296L; }
    p->head = (int)v;
    p->tail = 0;
    *link = p; link = &p->tail;
  }
  /* phase 2 — the call under test */
  r = IntList_append(xs, ys);
  /* phase 3 — WALKER/SERIALIZER (idiom fragment): cap-guarded walk,
     re-encode with the builder's wire codec */
  m = 0u;
  for (p = r; p != 0 && m <= 16u; p = p->tail) { m = m + 1u; }
  if (m > 16u) { return 253; }
  out[0] = (unsigned char)(m % 256u);
  out[1] = (unsigned char)(m / 256u);
  j = 2u;
  for (p = r; p != 0; p = p->tail) {
    v = (long)p->head;
    if (v < 0) { v = v + 4294967296L; }
    out[j] = (unsigned char)(v % 256u);
    out[j + 1u] = (unsigned char)((v / 256u) % 256u);
    out[j + 2u] = (unsigned char)((v / 65536u) % 256u);
    out[j + 3u] = (unsigned char)((v / 16777216u) % 256u);
    j = j + 4u;
  }
  /* phase 4 — teardown: free the result list (leak-freedom: the
     healthy target reuses every node, so after this walk the harness
     owns no heap) */
  p = r;
  while (p != 0) { t = p->tail; free(p); p = t; }
  /* phase 5 — verdict: generic mismatch-index comparator (Form 1) */
  obs = 2u + 4u * m;
  if (sizeof(expected) != obs) { return 255; }
  for (i = 0u; i < obs; i++) {
    if (out[i] != expected[i]) { return (int)(1u + i); }
  }
  return 0;
}
