/* SpecLab linked-list harness (list BUILD-ONLY: builder-walker round trip).
   Generated by SpecLab.mkHarness — do not edit by hand.
   Idiom lineage: golean three-phase harness (setup - call - test);
   see lean_frontend/speclab/README.md. */

void *malloc(unsigned long size);
void free(void *p);

/* TARGET — verbatim from deps/cn/tests/cn/append.c
   (rems-project/cn, BSD-2-Clause; clean-room source per the
   2026-08-22 corpus ruling). The same file's `split` and `main` are
   not part of this rung. CN annotations ride along as ordinary
   comments (cabs-json filters magic comments — arc-15 S0 probe (c)). */

struct int_list {
  int head;
  struct int_list* tail;
};

/*@
datatype seq {
  Seq_Nil {},
  Seq_Cons {i32 head, datatype seq tail}
}

function [rec] (datatype seq) append(datatype seq xs, datatype seq ys) {
  match xs {
    Seq_Nil {} => {
      ys
    }
    Seq_Cons {head : h, tail : zs}  => {
      Seq_Cons {head: h, tail: append(zs, ys)}
    }
  }
}

predicate [rec] (datatype seq) IntList(pointer p) {
  if (is_null(p)) {
    return Seq_Nil{};
  } else {
    take H = RW<struct int_list>(p);
    take tl = IntList(H.tail);
    return (Seq_Cons { head: H.head, tail: tl });
  }
}
@*/

struct int_list* IntList_append(struct int_list* xs, struct int_list* ys)
/*@ requires take L1 = IntList(xs);
             take L2 = IntList(ys);
    ensures take L3 = IntList(return);
            L3 == append(L1, L2); @*/
{
  if (xs == 0) {
    /*@ unfold append(L1, L2); @*/
    return ys;
  } else {
    /*@ unfold append(L1, L2); @*/
    struct int_list *new_tail = IntList_append(xs->tail, ys);
    xs->tail = new_tail;
    return xs;
  }
}

int main(void)
{
  const unsigned char choices[] = { 2, 0, 1, 2, 3, 4, 5, 6, 7, 8, 1, 0, 9, 10, 11, 12 };
  const unsigned char expected[] = { 2, 0, 1, 2, 3, 4, 5, 6, 7, 8, 1, 0, 9, 10, 11, 12 };
  struct int_list *xs;
  struct int_list *ys;
  struct int_list *r;
  struct int_list *p;
  struct int_list *t;
  struct int_list **link;
  unsigned char out[68]; /* max obs: append 2+4*16=66; build-only 4+4*16=68 */
  unsigned long i, j, m, n1, n2, off, obs;
  long v;
  /* phase 0 — stream validity (total on any splice):
     u16le(n1) ++ n1 x i32le ++ u16le(n2) ++ n2 x i32le; caps 8/8 */
  if (sizeof(choices) < 2u) { return 254; }
  n1 = (unsigned long)choices[0] + 256u * (unsigned long)choices[1];
  if (n1 > 8u) { return 254; }
  if (sizeof(choices) < 4u + 4u * n1) { return 254; }
  n2 = (unsigned long)choices[2u + 4u * n1]
     + 256u * (unsigned long)choices[3u + 4u * n1];
  if (n2 > 8u) { return 254; }
  if (sizeof(choices) != 4u + 4u * n1 + 4u * n2) { return 254; }
  /* phase 1 — BUILDER (idiom fragment): stream-driven list
     constructor — node-by-node malloc, tail-link threading, i32le
     element codec, two's-complement into int (UB-free) */
  xs = 0; link = &xs;
  for (i = 0u; i < n1; i++) {
    p = (struct int_list*)malloc(sizeof(struct int_list));
    if (p == 0) { return 252; }
    off = 2u + 4u * i;
    v = (long)((unsigned long)choices[off]
        + 256u * (unsigned long)choices[off + 1u]
        + 65536u * (unsigned long)choices[off + 2u]
        + 16777216u * (unsigned long)choices[off + 3u]);
    if (v >= 2147483648L) { v = v - 4294967296L; }
    p->head = (int)v;
    p->tail = 0;
    *link = p; link = &p->tail;
  }
  ys = 0; link = &ys;
  for (i = 0u; i < n2; i++) {
    p = (struct int_list*)malloc(sizeof(struct int_list));
    if (p == 0) { return 252; }
    off = 4u + 4u * n1 + 4u * i;
    v = (long)((unsigned long)choices[off]
        + 256u * (unsigned long)choices[off + 1u]
        + 65536u * (unsigned long)choices[off + 2u]
        + 16777216u * (unsigned long)choices[off + 3u]);
    if (v >= 2147483648L) { v = v - 4294967296L; }
    p->head = (int)v;
    p->tail = 0;
    *link = p; link = &p->tail;
  }
  /* phase 2 — NO call (builder-correctness instance) */
  /* phase 3 — serialize xs then ys with the wire codec */
  out[0] = (unsigned char)(n1 % 256u);
  out[1] = (unsigned char)(n1 / 256u);
  j = 2u;
  for (p = xs; p != 0; p = p->tail) {
    v = (long)p->head;
    if (v < 0) { v = v + 4294967296L; }
    out[j] = (unsigned char)(v % 256u);
    out[j + 1u] = (unsigned char)((v / 256u) % 256u);
    out[j + 2u] = (unsigned char)((v / 65536u) % 256u);
    out[j + 3u] = (unsigned char)((v / 16777216u) % 256u);
    j = j + 4u;
  }
  out[j] = (unsigned char)(n2 % 256u);
  out[j + 1u] = (unsigned char)(n2 / 256u);
  j = j + 2u;
  for (p = ys; p != 0; p = p->tail) {
    v = (long)p->head;
    if (v < 0) { v = v + 4294967296L; }
    out[j] = (unsigned char)(v % 256u);
    out[j + 1u] = (unsigned char)((v / 256u) % 256u);
    out[j + 2u] = (unsigned char)((v / 65536u) % 256u);
    out[j + 3u] = (unsigned char)((v / 16777216u) % 256u);
    j = j + 4u;
  }
  /* phase 4 — teardown: free both lists */
  p = xs;
  while (p != 0) { t = p->tail; free(p); p = t; }
  p = ys;
  while (p != 0) { t = p->tail; free(p); p = t; }
  /* phase 5 — verdict: generic mismatch-index comparator */
  obs = 4u + 4u * (n1 + n2);
  if (sizeof(expected) != obs) { return 255; }
  for (i = 0u; i < obs; i++) {
    if (out[i] != expected[i]) { return (int)(1u + i); }
  }
  return 0;
}
