/* SpecLab divmod harness (Form 1u-i8: kernel instance, unrolled, i8 stream).
   Generated by SpecLab.mkHarness — do not edit by hand.
   Idiom lineage: golean three-phase harness (setup - call - test);
   see lean_frontend/speclab/README.md. */

/* TARGETS — verbatim from deps/cn/tests/cn/division.c and
   deps/cn/tests/cn/mod.c (rems-project/cn, BSD-2-Clause; clean-room
   source per the 2026-08-22 corpus ruling). CN annotations ride
   along as ordinary comments (cabs-json filters magic comments —
   arc-15 S0 probe (c)). */

int division (int x, int y)
/*@ requires y != 0i32;
    ensures return == x/y; @*/
{
    return x / y;
}

int mod (int x, int y)
/*@ requires y != 0i32;
    ensures return == x % y; @*/
{
    return x % y;
}

int main(void)
{
  const unsigned char choices[2] = { 250, 3 };
  const unsigned char expected[4] = { 254, 255, 0, 0 };
  int x, y, q, r;
  /* phase 1 — builder: two i8 values from the choice stream */
  x = (int)choices[0]; if (x >= 128) { x = x - 256; }
  y = (int)choices[1]; if (y >= 128) { y = y - 256; }
  /* phase 2 — the calls under test */
  q = division(x, y);
  r = mod(x, y);
  /* phase 3 — observation: i16le-encode both results;
     verdict — unrolled mismatch-index comparator */
  if (q < 0) { q = q + 65536; }
  if (r < 0) { r = r + 65536; }
  if (sizeof(choices) != 2u || sizeof(expected) != 4u) { return 255; }
  if ((unsigned char)(q % 256) != expected[0]) { return 1; }
  if ((unsigned char)(q / 256) != expected[1]) { return 2; }
  if ((unsigned char)(r % 256) != expected[2]) { return 3; }
  if ((unsigned char)(r / 256) != expected[3]) { return 4; }
  return 0;
}
