/* SpecLab byte-blaster harness (get_from_arr Form 1, WRONG-INDEX PLANT).
   Generated by SpecLab.mkHarness — do not edit by hand.
   Idiom lineage: golean three-phase harness (setup - call - test);
   see lean_frontend/speclab/README.md. */

/* TARGET — PLANT VARIANT (template-note §plant-test): get_from_arr
   is deliberately BROKEN (wrong index: reads in_arr[3], not
   in_arr[4]). A healthy-looking verdict from this program on inputs
   with in_arr[3] != in_arr[4] means the harness is vacuous. */

char
get_from_arr (char *in_arr)
{
  char c;

  c = in_arr[3]; /* PLANT: wrong index */

  return c;
}

int main(void)
{
  const unsigned char choices[] = { 104, 101, 108, 108, 111, 104, 101, 108, 108, 111 };
  const unsigned char expected[] = { 111, 104, 101, 108, 108, 111, 104, 101, 108, 108, 111 };
  char arr[10];
  unsigned char out[11];
  unsigned long i;
  int v, w;
  /* phase 0 — stream validity: exactly the CN resource extent */
  if (sizeof(choices) != 10u) { return 254; }
  /* phase 1 — builder: byte-blast the stream into arr */
  for (i = 0u; i < 10u; i++) {
    v = (int)choices[i]; if (v >= 128) { v = v - 256; }
    arr[i] = (char)v;
  }
  /* phase 2 — the call under test (interior of the built array) */
  v = (int)get_from_arr(arr);
  if (v < 0) { v = v + 256; }
  /* phase 3 — observation: ret ++ arr[0..10);
     verdict — generic mismatch-index comparator (Form 1) */
  out[0] = (unsigned char)v;
  for (i = 0u; i < 10u; i++) {
    w = (int)arr[i]; if (w < 0) { w = w + 256; }
    out[1u + i] = (unsigned char)w;
  }
  if (sizeof(expected) != 11u) { return 255; }
  for (i = 0u; i < 11u; i++) {
    if (out[i] != expected[i]) { return (int)(1u + i); }
  }
  return 0;
}
