/* SpecLab byte-blaster harness (get_from_arr Form 1: byte-blaster, mismatch-index).
   Generated by SpecLab.mkHarness — do not edit by hand.
   Idiom lineage: golean three-phase harness (setup - call - test);
   see lean_frontend/speclab/README.md. */

/* TARGET — verbatim from deps/cn/tests/cn/get_from_arr.c
   (rems-project/cn, BSD-2-Clause; clean-room source per the
   2026-08-22 corpus ruling; upstream header: "originally made by
   minimising a problematic case from memcpy.c"). NOTE the CN
   ensures is OWNERSHIP-ONLY — it does not constrain the return
   value; this harness's spec is strictly stronger (register S2-E3). */

char
get_from_arr (char *in_arr)
/*@ requires take IA = each (i32 j; 0i32 <= j && j < 10i32)
  {RW<char>(in_arr + j)};
    ensures take IA2 = each (i32 j; 0i32 <= j && j < 10i32)
  {RW<char>(in_arr + j)}; @*/
{
  char c;

  /*@ focus RW<char>, 4i32; @*/
  /*@ instantiate good<char>, 4i32; @*/
  c = in_arr[4];

  return c;
}

int main(void)
{
  const unsigned char choices[] = { 0, 255, 0, 255, 7, 0, 255, 0, 255, 127 };
  const unsigned char expected[] = { 7, 0, 255, 0, 255, 7, 0, 255, 0, 255, 127 };
  char arr[10];
  unsigned char out[11];
  unsigned long i;
  int v, w;
  /* phase 0 — stream validity: exactly the CN resource extent */
  if (sizeof(choices) != 10u) { return 254; }
  /* phase 1 — builder: byte-blast the stream into arr */
  for (i = 0u; i < 10u; i++) {
    v = (int)choices[i]; if (v >= 128) { v = v - 256; }
    arr[i] = (char)v;
  }
  /* phase 2 — the call under test (interior of the built array) */
  v = (int)get_from_arr(arr);
  if (v < 0) { v = v + 256; }
  /* phase 3 — observation: ret ++ arr[0..10);
     verdict — generic mismatch-index comparator (Form 1) */
  out[0] = (unsigned char)v;
  for (i = 0u; i < 10u; i++) {
    w = (int)arr[i]; if (w < 0) { w = w + 256; }
    out[1u + i] = (unsigned char)w;
  }
  if (sizeof(expected) != 11u) { return 255; }
  for (i = 0u; i < 11u; i++) {
    if (out[i] != expected[i]) { return (int)(1u + i); }
  }
  return 0;
}
