/* SpecLab CN-seed harness (lookup_size_shift Form 1: enum scalar, mismatch-index).
   Generated by SpecLab.mkHarness — do not edit by hand.
   Idiom lineage: golean three-phase harness (setup - call - test);
   see lean_frontend/speclab/README.md. */

/* TARGET — verbatim from deps/cn/tests/cn/cn_inline.c
   (rems-project/cn, BSD-2-Clause; clean-room source per the
   2026-08-22 corpus ruling; the file's f() and trusted main are
   replaced by this harness). CN annotations ride along as ordinary
   comments (arc-15 S0 probe (c)). */

enum size {
  big,
  medium,
  small,
};

/*@ function (i32) lookup_size_shift_cn (u32 sz) @*/

static inline int
lookup_size_shift (enum size sz)
/*@ cn_function lookup_size_shift_cn;
    ensures return == lookup_size_shift_cn(sz); @*/
{
  switch (sz) {
    case big:
      return 12;
    case medium:
      return 8;
    case small:
      return 2;
    default:
      /* shouldn't happen */
      return 0;
  }
}

int main(void)
{
  const unsigned char choices[] = { 2, 0, 0, 0 };
  const unsigned char expected[] = { 2, 0, 0, 0 };
  unsigned char out[4];
  unsigned long i;
  long acc;
  int v, r;
  /* phase 0 — stream validity (total on any splice): u32le sz,
     int-representable (the enum argument's build ceiling) */
  if (sizeof(choices) != 4u) { return 254; }
  acc = 0L;
  for (i = 0u; i < 4u; i++) { acc = acc + ((long)choices[i] << (8u * i)); }
  if (acc >= 2147483648L) { return 254; }
  v = (int)acc;
  /* phase 2 — the call under test (int -> enum size conversion) */
  r = lookup_size_shift((enum size)v);
  /* phase 3 — observation: i32le(ret);
     verdict — generic mismatch-index comparator (Form 1) */
  acc = (long)r; if (acc < 0L) { acc = acc + 4294967296L; }
  for (i = 0u; i < 4u; i++) { out[i] = (unsigned char)(acc % 256L); acc = acc / 256L; }
  if (sizeof(expected) != 4u) { return 255; }
  for (i = 0u; i < 4u; i++) {
    if (out[i] != expected[i]) { return (int)(1u + i); }
  }
  return 0;
}
