/* SpecLab byte-blaster harness (memcpy Form 1, OFF-BY-ONE PLANT).
   Generated by SpecLab.mkHarness — do not edit by hand.
   Idiom lineage: golean three-phase harness (setup - call - test);
   see lean_frontend/speclab/README.md. */

/* TARGET — PLANT VARIANT (template-note §plant-test): naive_memcpy
   is deliberately BROKEN (off-by-one: the copy loop starts at i = 1,
   so dst[0] keeps the harness canary). A healthy-looking verdict
   from this program means the harness is vacuous. */

void
naive_memcpy (char *dst, char *src, int n)
{
  int i;
  for (i = 1; i < n; i = i + 1) /* PLANT: off-by-one (i = 1) */
  {
    dst[i] = src[i];
  }
}

int main(void)
{
  const unsigned char choices[] = { 3, 0, 1, 2, 3 };
  const unsigned char expected[] = { 3, 0, 1, 2, 3, 1, 2, 3 };
  char src[16];
  char dst[16];
  unsigned char out[34];
  unsigned long i, n, obs;
  int v, w;
  /* phase 0 — stream validity (the harness is total on any splice):
     u16le length prefix, capacity 16 */
  if (sizeof(choices) < 2u) { return 254; }
  n = (unsigned long)choices[0] + 256u * (unsigned long)choices[1];
  if (n > 16u) { return 254; }
  if (sizeof(choices) != 2u + n) { return 254; }
  /* phase 1 — builder: byte-blast the stream into src (two's-
     complement into char, UB-free); canary-fill dst */
  for (i = 0u; i < n; i++) {
    v = (int)choices[2u + i]; if (v >= 128) { v = v - 256; }
    src[i] = (char)v;
  }
  for (i = 0u; i < 16u; i++) { dst[i] = 42; }
  /* phase 2 — the call under test: (ptr, len) */
  naive_memcpy(dst, src, (int)n);
  /* phase 3 — observation: u16le(n) ++ dst[0..n) ++ src[0..n);
     verdict — generic mismatch-index comparator (Form 1) */
  out[0] = (unsigned char)(n % 256u);
  out[1] = (unsigned char)(n / 256u);
  for (i = 0u; i < n; i++) {
    w = (int)dst[i]; if (w < 0) { w = w + 256; }
    out[2u + i] = (unsigned char)w;
  }
  for (i = 0u; i < n; i++) {
    w = (int)src[i]; if (w < 0) { w = w + 256; }
    out[2u + n + i] = (unsigned char)w;
  }
  obs = 2u + 2u * n;
  if (sizeof(expected) != obs) { return 255; }
  for (i = 0u; i < obs; i++) {
    if (out[i] != expected[i]) { return (int)(1u + i); }
  }
  return 0;
}
