/* SpecLab CN-seed harness (swap_pair Form 1, LOST-UPDATE PLANT).
   Generated by SpecLab.mkHarness — do not edit by hand.
   Idiom lineage: golean three-phase harness (setup - call - test);
   see lean_frontend/speclab/README.md. */

/* TARGET — PLANT VARIANT (template-note §plant-test): swap_pair is
   deliberately BROKEN (lost update: the restore step reads the
   already-overwritten cell instead of tmp). A healthy-looking
   verdict from this program off the a = b diagonal means the
   harness is vacuous. */

void swap_pair(unsigned long int *pair_p)
{
    unsigned long int tmp = pair_p[0];
    pair_p[0] = pair_p[1];
    pair_p[1] = pair_p[0]; /* PLANT: lost update (should be tmp) */
}

int main(void)
{
  const unsigned char choices[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 };
  const unsigned char expected[] = { 9, 10, 11, 12, 13, 14, 15, 16, 1, 2, 3, 4, 5, 6, 7, 8 };
  unsigned long int pair[2];
  unsigned char out[16];
  unsigned long i, j, acc;
  /* phase 0 — stream validity (total on any splice): exactly the CN
     resource extent, two u64 cells */
  if (sizeof(choices) != 16u) { return 254; }
  /* phase 1 — builder: two u64le values from the choice stream */
  for (j = 0u; j < 2u; j++) {
    acc = 0ul;
    for (i = 0u; i < 8u; i++) {
      acc = acc + ((unsigned long)choices[8u*j + i] << (8u * i));
    }
    pair[j] = acc;
  }
  /* phase 2 — the call under test (the built array's own pointer) */
  swap_pair(pair);
  /* phase 3 — observation: both post-state cells, u64le;
     verdict — generic mismatch-index comparator (Form 1) */
  for (j = 0u; j < 2u; j++) {
    acc = pair[j];
    for (i = 0u; i < 8u; i++) {
      out[8u*j + i] = (unsigned char)(acc % 256u);
      acc = acc / 256u;
    }
  }
  if (sizeof(expected) != 16u) { return 255; }
  for (i = 0u; i < 16u; i++) {
    if (out[i] != expected[i]) { return (int)(1u + i); }
  }
  return 0;
}
