/* SpecLab CN-seed harness (swap_pair Form 1: u64 pair, mismatch-index).
   Generated by SpecLab.mkHarness — do not edit by hand.
   Idiom lineage: golean three-phase harness (setup - call - test);
   see lean_frontend/speclab/README.md. */

/* TARGET — verbatim from deps/cn/tests/cn/swap_pair.c
   (rems-project/cn, BSD-2-Clause; clean-room source per the
   2026-08-22 corpus ruling; the file's own trusted main is replaced
   by this harness). CN annotations ride along as ordinary comments
   (cabs-json filters magic comments — arc-15 S0 probe (c)). */

void swap_pair(unsigned long int *pair_p)
/*@
requires
    take pairStart = each (i32 j; 0i32 <= j && j < 2i32) {RW(array_shift(pair_p, j))};
ensures
    take pairEnd = each (i32 j; 0i32 <= j && j < 2i32) {RW(array_shift(pair_p, j))};
    pairEnd[0i32] == pairStart[1i32];
    pairEnd[1i32] == pairStart[0i32];
@*/
{
    /*@ focus RW<unsigned long int>, 0i32; @*/
    unsigned long int tmp = pair_p[0];
    /*@ focus RW<unsigned long int>, 1i32; @*/
    /*@ instantiate good<unsigned long int>, 0i32; @*/
    pair_p[0] = pair_p[1];
    /*@ instantiate good<unsigned long int>, 1i32; @*/
    pair_p[1] = tmp;
}

int main(void)
{
  const unsigned char choices[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 };
  const unsigned char expected[] = { 9, 10, 11, 12, 13, 14, 15, 16, 1, 2, 3, 4, 5, 6, 7, 8 };
  unsigned long int pair[2];
  unsigned char out[16];
  unsigned long i, j, acc;
  /* phase 0 — stream validity (total on any splice): exactly the CN
     resource extent, two u64 cells */
  if (sizeof(choices) != 16u) { return 254; }
  /* phase 1 — builder: two u64le values from the choice stream */
  for (j = 0u; j < 2u; j++) {
    acc = 0ul;
    for (i = 0u; i < 8u; i++) {
      acc = acc + ((unsigned long)choices[8u*j + i] << (8u * i));
    }
    pair[j] = acc;
  }
  /* phase 2 — the call under test (the built array's own pointer) */
  swap_pair(pair);
  /* phase 3 — observation: both post-state cells, u64le;
     verdict — generic mismatch-index comparator (Form 1) */
  for (j = 0u; j < 2u; j++) {
    acc = pair[j];
    for (i = 0u; i < 8u; i++) {
      out[8u*j + i] = (unsigned char)(acc % 256u);
      acc = acc / 256u;
    }
  }
  if (sizeof(expected) != 16u) { return 255; }
  for (i = 0u; i < 16u; i++) {
    if (out[i] != expected[i]) { return (int)(1u + i); }
  }
  return 0;
}
