/* SpecLab tree-rotation harness (rotate_right Form 1: tree builder, path-selected locus, mismatch-index).
   Generated by SpecLab.mkHarness — do not edit by hand.
   Idiom lineage: golean three-phase harness (setup - call - test);
   see lean_frontend/speclab/README.md. */

void *malloc(unsigned long size);
void free(void *p);

/* TARGET — fresh authorship for arc-15 R4 (the deps/cn corpus has no
   rotation; struct shape follows the corpus int-binary-tree
   reference, deps/cn/tests/cn/tree_rev01.c). CN-style contract, for
   the record (informal here — this rung's spec IS the harness
   statement):
     requires take T = Tree(t);
     ensures  take T2 = Tree(return); T2 == rotate_right_spec(T);

        t             l
       / \           / \
      l   r   ==>  ll   t
     / \               / \
    ll  lr            lr  r
*/

struct node {
  int val;
  struct node *left;
  struct node *right;
};

struct node* rotate_right(struct node *t)
{
  struct node *l;
  if (t == 0) { return t; }
  if (t->left == 0) { return t; }
  l = t->left;
  t->left = l->right;
  l->right = t;
  return l;
}

/* --- the R4 idiom trio: recursive tree helpers ------------------- */

/* phase 0 helper — stream validity: recursive pre-order scan of one
   tree encoding (NO allocation; malformed input never allocates).
   Returns bytes consumed, or -1 on malformed/over-capacity input;
   cnt accumulates the node count against the 31-node cap. */
static long scan_tree(unsigned char *c, unsigned long len,
                      unsigned long pos, unsigned long *cnt)
{
  long lsub, rsub;
  if (pos >= len) { return -1; }
  if (c[pos] == 0u) { return 1; }
  if (c[pos] != 1u) { return -1; }
  if (pos + 5u > len) { return -1; }
  *cnt = *cnt + 1u;
  if (*cnt > 31u) { return -1; }
  lsub = scan_tree(c, len, pos + 5u, cnt);
  if (lsub < 0) { return -1; }
  rsub = scan_tree(c, len, pos + 5u + (unsigned long)lsub, cnt);
  if (rsub < 0) { return -1; }
  return 5 + lsub + rsub;
}

/* phase 1 helper — BUILDER: stream-driven recursive pre-order heap
   constructor (runs only on scan-validated streams; the only
   remaining failure is allocator refusal — the 252 totality arm,
   model-side unreachable — reported through *err). i32le val,
   two's-complement into int, UB-free. */
static struct node *build_tree(unsigned char *c, unsigned long *pos,
                               int *err)
{
  struct node *t;
  struct node *lch;
  struct node *rch;
  unsigned long off;
  long v;
  if (*err != 0) { return 0; }
  if (c[*pos] == 0u) { *pos = *pos + 1u; return 0; }
  off = *pos + 1u;
  *pos = *pos + 5u;
  t = (struct node*)malloc(sizeof(struct node));
  if (t == 0) { *err = 252; return 0; }
  v = (long)((unsigned long)c[off]
      + 256u * (unsigned long)c[off + 1u]
      + 65536u * (unsigned long)c[off + 2u]
      + 16777216u * (unsigned long)c[off + 3u]);
  if (v >= 2147483648L) { v = v - 4294967296L; }
  t->val = (int)v;
  /* SEQUENCED-CALL RULE (register S4-E): call results land in plain
     locals before any member/deref store — a deref-store of a call
     result is an unsequenced pair that MULTIPLIES exhaustive-mode
     interleavings (measured: 3 executions per site; the S3 append
     harness complied by accident via its initializer style). */
  lch = build_tree(c, pos, err);
  t->left = lch;
  rch = build_tree(c, pos, err);
  t->right = rch;
  return t;
}

/* phase 3 helper — WALKER/SERIALIZER: cap-guarded recursive
   pre-order re-encoding of the post-state tree with the builder's
   wire codec. Returns the next write index, or -1 once the 31-node
   budget is exhausted (the 253 overlong arm — keeps every target
   variant total: a cycle-creating target cannot hang the harness).
   Write bound: at most 31 node records (5 bytes) + 32 leaf bytes =
   187 <= sizeof(out). */
static long serialize_tree(struct node *t, unsigned char *out,
                           long j, unsigned long *cnt)
{
  long v;
  if (t == 0) { out[j] = 0u; return j + 1; }
  *cnt = *cnt + 1u;
  if (*cnt > 31u) { return -1; }
  out[j] = 1u;
  v = (long)t->val;
  if (v < 0) { v = v + 4294967296L; }
  out[j + 1] = (unsigned char)((unsigned long)v % 256u);
  out[j + 2] = (unsigned char)(((unsigned long)v / 256u) % 256u);
  out[j + 3] = (unsigned char)(((unsigned long)v / 65536u) % 256u);
  out[j + 4] = (unsigned char)(((unsigned long)v / 16777216u) % 256u);
  j = serialize_tree(t->left, out, j + 5, cnt);
  if (j < 0) { return -1; }
  return serialize_tree(t->right, out, j, cnt);
}

/* phase 4 helper — teardown: recursive free of a serializer-validated
   tree (leak-freedom: rotation is allocation-neutral — the healthy
   post-state reaches every built node). */
static void free_tree(struct node *t)
{
  if (t == 0) { return; }
  free_tree(t->left);
  free_tree(t->right);
  free(t);
}

int main(void)
{
  unsigned char choices[] = { 1, 0, 0, 0, 0, 1, 255, 255, 255, 255, 1, 0, 0, 0, 128, 0, 1, 255, 255, 255, 127, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 128, 0, 0, 1, 0 };
  unsigned char expected[] = { 1, 0, 0, 0, 0, 1, 0, 0, 0, 128, 0, 1, 255, 255, 255, 255, 1, 255, 255, 255, 127, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 128, 0, 0 };
  struct node *root;
  struct node **link;
  struct node *newsub;
  unsigned char out[200]; /* max obs: rotate 187; build-only 196 */
  unsigned long i, cnt, pos, bpos, plen, obs;
  long consumed, j;
  int err;
  /* phase 0 — stream validity (total on any splice; no allocation on
     malformed input): pre-order tree code (scan_tree) ++ u8(plen) ++
     plen path bytes (each 0/1); caps: 31 nodes, 8 path steps. */
  cnt = 0u;
  consumed = scan_tree(choices, sizeof(choices), 0u, &cnt);
  if (consumed < 0) { return 254; }
  pos = (unsigned long)consumed;
  if (pos >= sizeof(choices)) { return 254; }
  plen = (unsigned long)choices[pos];
  if (plen > 8u) { return 254; }
  if (sizeof(choices) != pos + 1u + plen) { return 254; }
  for (i = 0u; i < plen; i++) {
    if (choices[pos + 1u + i] > 1u) { return 254; }
  }
  /* phase 1 — build the tree from the stream */
  err = 0;
  bpos = 0u;
  root = build_tree(choices, &bpos, &err);
  if (err != 0) { return err; }
  /* phase 2 — POINTER SELECTION + the call under test: walk the
     built tree along the path to the rotation locus; the target gets
     THE INTERIOR POINTER the walk arrives at (pointer values never
     appear in the stream), and the parent link takes the returned
     subtree root — exactly as a caller of rotate_right would. */
  link = &root;
  for (i = 0u; i < plen && *link != 0; i++) {
    if (choices[pos + 1u + i] == 1u) { link = &(*link)->right; }
    else { link = &(*link)->left; }
  }
  newsub = rotate_right(*link); /* sequenced-call rule (S4-E) */
  *link = newsub;
  /* phase 3 — serialize the post-state tree (cap-guarded) */
  cnt = 0u;
  j = serialize_tree(root, out, 0, &cnt);
  if (j < 0) { return 253; }
  /* phase 4 — teardown: free the post-state tree */
  free_tree(root);
  /* phase 5 — verdict: generic mismatch-index comparator (Form 1) */
  obs = (unsigned long)j;
  if (sizeof(expected) != obs) { return 255; }
  for (i = 0u; i < obs; i++) {
    if (out[i] != expected[i]) { return (int)(1u + i); }
  }
  return 0;
}
