/-
  Arc-3 totality proofs (S3), restated for the fuel-parameter arc
  (2026-09-04; docs/2026-09-04_fuel-parameter-C1-record.md).

  Part 1 — FUEL PARAMETRICITY: for EVERY fuel'd def in the generated
  tree, the wrapper at an arbitrary `[LemFuel]` instance `⟨n⟩` is
  definitionally the worker started at `n` — `@f ⟨n⟩ = f_lemFuel n`, for
  all `n`, by `rfl` (the wrapper is `f_lemFuel LemFuel.fuel` and
  `LemFuel.fuel ⟨n⟩` is `n` by projection). A worker that passes the
  ambient on to its own fuel'd callees (the driver family, the
  substitution family, …) carries the instance itself, so its right-hand
  side reads `@f_lemFuel ⟨n⟩ n`. The former statement — "wrapper = worker
  at `lemDefaultFuel` / `CerbFuel.driverFuel`" — was the instance
  `n := 10^6` / `n := 10^8` of these; the constants are DELETED
  ([USER 2026-09-03]: magic values are definitionally bugs). Provable by
  rfl only because both sides exist as total defs with equations; each
  `example` is universally quantified over the def's type and class
  binders (read from the generated heads, so a drift fails this build).
  The list is the generated tree's ambient-wrapper set, regenerated by
  `scripts/gen_fuel_parametricity.py --emit` from the `def f … [LemFuel] :
  … := f_lemFuel LemFuel.fuel` lines (64 at C1); `scripts/gen_fuel_parametricity.py
  --check`, run by `test_unit.sh`, pins the SET both directions — a new
  fuel'd wrapper without a pin, or a pin without a wrapper, is RED
  (pre-merge audit M1). The three MEASURED equalities
  (`ctypeEqual`/`eq_core_base_type`/`fake_mem_value_eq`) are not ambient
  wrappers; their fuel-freedom is pinned by their sufficiency obligations.

  Part 2 (below) — symbolic execution theorems over the total spine.

  Compile-time proofs; main reports success at runtime.
-/

import LemLib
import CerbFuel
import AilTypesAux
import Core_aux
import Core_eval
import Core_reduction
import Core_run_aux
import Ctype_aux
import Defacto_memory
import Defacto_memory_aux
import Driver
import Formatted
import Monadic_parsing
import Nondeterminism
import Utils

open Lem_Basic_classes Lem_Map
set_option autoImplicit true

/-! ### Part 1: fuel parametricity, one per fuel'd def -/

-- 29 ambient wrappers (generated by scripts/gen_fuel_parametricity.py --emit from the generated tree; scripts/gen_fuel_parametricity.py --check pins this SET in test_unit.sh)
example (n : Nat) : @are_compatible ⟨n⟩ = @are_compatible_lemFuel n := rfl
example (n : Nat) : @are_compatible_params_aux ⟨n⟩ = @are_compatible_params_aux_lemFuel n := rfl
example (n : Nat) : @are_compatible_params ⟨n⟩ = @are_compatible_params_lemFuel n := rfl
example {a : Type} (n : Nat) : @zeros_aux a ⟨n⟩ = @zeros_aux_lemFuel a n := rfl
example {a : Type} (n : Nat) : @to_pure a ⟨n⟩ = @to_pure_lemFuel a n := rfl
example {a : Type} (n : Nat) : @to_pures a ⟨n⟩ = @to_pures_lemFuel a n := rfl
example (n : Nat) : @eval_pexpr_aux2 ⟨n⟩ = @eval_pexpr_aux2_lemFuel ⟨n⟩ n := rfl
example (n : Nat) : @eval_pexpr_aux_broken ⟨n⟩ = @eval_pexpr_aux_broken_lemFuel ⟨n⟩ n := rfl
example {b : Type} (n : Nat) : @full_eval_pexpr b ⟨n⟩ = @full_eval_pexpr_lemFuel b ⟨n⟩ n := rfl
example {a b : Type} (n : Nat) : @one_step_unseq_aux a b ⟨n⟩ = @one_step_unseq_aux_lemFuel a b n := rfl
example (n : Nat) : @get_ctx ⟨n⟩ = @get_ctx_lemFuel n := rfl
example (n : Nat) : @get_ctx_unseq_aux ⟨n⟩ = @get_ctx_unseq_aux_lemFuel n := rfl
example (n : Nat) : @are_compatible_params_aux0 ⟨n⟩ = @are_compatible_params_aux0_lemFuel ⟨n⟩ n := rfl
example (n : Nat) : @are_compatible_params0 ⟨n⟩ = @are_compatible_params0_lemFuel ⟨n⟩ n := rfl
example (n : Nat) : @are_compatible_aux ⟨n⟩ = @are_compatible_aux_lemFuel ⟨n⟩ n := rfl
example (n : Nat) : @mkUnspec ⟨n⟩ = @mkUnspec_lemFuel n := rfl
example (n : Nat) : @simplify_integer_value_base ⟨n⟩ = @simplify_integer_value_base_lemFuel n := rfl
example (n : Nat) : @print_eval_conv_aux ⟨n⟩ = @print_eval_conv_aux_lemFuel ⟨n⟩ n := rfl
example (n : Nat) : @drive_nonmemory_steps_aux2 ⟨n⟩ = @drive_nonmemory_steps_aux2_lemFuel ⟨n⟩ n := rfl
example (n : Nat) : @driver2 ⟨n⟩ = @driver2_lemFuel ⟨n⟩ n := rfl
example (n : Nat) : @hack ⟨n⟩ = @hack_lemFuel ⟨n⟩ n := rfl
example (n : Nat) : @showNonNegativeWithBasis_aux ⟨n⟩ = @showNonNegativeWithBasis_aux_lemFuel n := rfl
example (n : Nat) : @load_character_array_aux ⟨n⟩ = @load_character_array_aux_lemFuel ⟨n⟩ n := rfl
example {a : Type} (n : Nat) : @many a ⟨n⟩ = @many_lemFuel a n := rfl
example {a : Type} (n : Nat) : @many1 a ⟨n⟩ = @many1_lemFuel a n := rfl
example {a b c d e f : Type} (n : Nat) : @nd_bind a b c d e f ⟨n⟩ = @nd_bind_lemFuel a b c d e f n := rfl
example {a cs err1 err2 info1 info2 st1 st2 : Type} (n : Nat) : @liftND a cs err1 err2 info1 info2 st1 st2 ⟨n⟩ = @liftND_lemFuel a cs err1 err2 info1 info2 st1 st2 n := rfl
example {a cs err1 err2 info1 info2 st1 st2 : Type} (n : Nat) : @liftAction a cs err1 err2 info1 info2 st1 st2 ⟨n⟩ = @liftAction_lemFuel a cs err1 err2 info1 info2 st1 st2 n := rfl
example {a b : Type} (n : Nat) : @list_unfoldr_aux a b ⟨n⟩ = @list_unfoldr_aux_lemFuel a b n := rfl

/-! ### Part 2: symbolic execution over the total exec slice.
    Every statement is SYMBOLIC in the fuel (any `Nat.succ f`), the
    annotations, and the payloads — kernel-checked by `rfl`, which no
    `partial def` admits (no equations). -/

/-- Pattern matching: the wildcard base pattern matches anything, binding
    nothing. -/
example (f : Nat) (an : List annot) (bty : core_base_type) (cval : value) :
    match_pattern_lemFuel (Nat.succ f) (Pattern an (CaseBase (none, bty))) cval
      = some [] := rfl

/-- Pattern matching: a variable base pattern binds the scrutinee. -/
example (f : Nat) (an : List annot) (bty : core_base_type) (s : sym) (cval : value) :
    match_pattern_lemFuel (Nat.succ f) (Pattern an (CaseBase (some s, bty))) cval
      = some [(s, cval)] := rfl

/-- Type-annotation erasure: converting a symbol pexpr erases the bty and
    keeps the symbol (symbolic in the erased annotation's VALUE too). -/
example (f : Nat) (an : List annot) (b : Type) (btyv : b) (s : sym) :
    convert_pexpr_lemFuel (Nat.succ f) (Pexpr an btyv (PEsym s))
      = Pexpr an () (PEsym s) := rfl

/-- Concurrency-call analysis: a pure expression contains no ccall — via the
    WORKER at symbolic fuel. -/
example (f : Nat) (an : List annot) (pe : generic_pexpr b a) :
    has_ccall_lemFuel (c := c) (Nat.succ f) (Expr an (Epure pe)) = false := rfl

/-- The same fact through the WRAPPER, which since C2 is MEASURED (no fuel
    binder): it unfolds definitionally through the worker at the derived size
    of its argument (`generic_expr.lemSize`, kernel-computable). -/
example (an : List annot) (pe : generic_pexpr b a) :
    @has_ccall a b c (Expr an (Epure pe)) = false := rfl

/-- Substitution: a value pexpr is untouched (values contain no symbols). -/
example (f : Nat) (s : sym) (cval : value) (an : List annot) (bty : Unit)
    (v : value) :
    subst_sym_pexpr_lemFuel (Nat.succ f) s cval (Pexpr an bty (PEval v))
      = Pexpr an bty (PEval v) := rfl

/-- Pattern occurrence: no symbol occurs in a wildcard base pattern. -/
example (f : Nat) (s : sym) (an : List annot) (bty : core_base_type) :
    in_pattern_lemFuel (Nat.succ f) s (Pattern an (CaseBase (none, bty)))
      = false := rfl

/-- Environment lookup on the empty environment stack (structural-total,
    no fuel needed). -/
example (s : sym) : lookup_env (a := value) s [] = none := rfl

def main : IO Unit :=
  IO.println "TotalityProofTest: all proofs kernel-checked at compile time (fuel parametricity of every fuel'd def + symbolic execution)"
