/-
SpecLab.CnSeedHarness — arc-15 S5: the CN-seed harness templates
(mechanism A instances over the SpecLab.CnSeed models).

BOTH templates are pure R1-R4 library assembly — Form 1 (the
S1-confirmed default: expected-array + generic mismatch-index
comparator), looped block-scope shape (S1-E4 `globs = []` rule), UB-
free builders/readbacks (S1 discipline: byte reassembly in unsigned/
long arithmetic, results re-encoded via explicit `+ 2^k`), totality
arms (254 malformed) making every splice a defined program. The
sequenced-call rule (S4-E2) is vacuous here — neither harness stores
a call result through a member/deref (swap_pair returns void into no
LHS; lookup's result lands in a plain local by construction).

VERDICT SPACES:
  swap:   0 / 1+i (i < 16) / 254 (stream ≠ 16 bytes) / 255
  lookup: 0 / 1+i (i < 4)  / 254 (stream ≠ 4 bytes ∨ sz ≥ 2^31) / 255

OBSERVATION LAYOUTS: swap — the post-call pair, u64le each (the CN
`ensures` reads back bytes-for-bytes: pairEnd[0] = pairStart[1],
pairEnd[1] = pairStart[0]); lookup — i32le(ret).

Targets cited verbatim (file + CN spec) per the S1 scoping rule; CN
magic comments ride along as ordinary comments (S0 probe (c)).
-/

import SpecLab.CnSeed

set_option autoImplicit false

namespace SpecLab
namespace CnSeed

/-- The verbatim swap_pair target, with citation + CN spec (healthy).
The corpus file's own `/*@ trusted; @*/` main is REPLACED by the
harness (the harness is the closed program). -/
def swapTargetHealthy : String :=
"/* TARGET — verbatim from deps/cn/tests/cn/swap_pair.c
   (rems-project/cn, BSD-2-Clause; clean-room source per the
   2026-08-22 corpus ruling; the file's own trusted main is replaced
   by this harness). CN annotations ride along as ordinary comments
   (cabs-json filters magic comments — arc-15 S0 probe (c)). */

void swap_pair(unsigned long int *pair_p)
/*@
requires
    take pairStart = each (i32 j; 0i32 <= j && j < 2i32) {RW(array_shift(pair_p, j))};
ensures
    take pairEnd = each (i32 j; 0i32 <= j && j < 2i32) {RW(array_shift(pair_p, j))};
    pairEnd[0i32] == pairStart[1i32];
    pairEnd[1i32] == pairStart[0i32];
@*/
{
    /*@ focus RW<unsigned long int>, 0i32; @*/
    unsigned long int tmp = pair_p[0];
    /*@ focus RW<unsigned long int>, 1i32; @*/
    /*@ instantiate good<unsigned long int>, 0i32; @*/
    pair_p[0] = pair_p[1];
    /*@ instantiate good<unsigned long int>, 1i32; @*/
    pair_p[1] = tmp;
}
"

/-- The swap PLANT target: the LOST-UPDATE bug (`pair_p[1]` takes the
already-overwritten `pair_p[0]`, not `tmp` — both cells end holding
the old pair_p[1]), loudly marked. Blind exactly on the diagonal
a = b (`swapPlant_blind_iff`, kernel-characterized). -/
def swapTargetPlant : String :=
"/* TARGET — PLANT VARIANT (template-note §plant-test): swap_pair is
   deliberately BROKEN (lost update: the restore step reads the
   already-overwritten cell instead of tmp). A healthy-looking
   verdict from this program off the a = b diagonal means the
   harness is vacuous. */

void swap_pair(unsigned long int *pair_p)
{
    unsigned long int tmp = pair_p[0];
    pair_p[0] = pair_p[1];
    pair_p[1] = pair_p[0]; /* PLANT: lost update (should be tmp) */
}
"

def header (form : String) : String :=
"/* SpecLab CN-seed harness (" ++ form ++ ").
   Generated by SpecLab.mkHarness — do not edit by hand.
   Idiom lineage: golean three-phase harness (setup - call - test);
   see lean_frontend/speclab/README.md. */

"

/-- The shared `pre` tail (block-scope arrays, S1-E4). -/
def preTail : String :=
"
int main(void)
{
  const unsigned char choices[] = { "

/-- The shared `mid`: close choices[], open expected[]. -/
def seedMid : String :=
  " };\n  const unsigned char expected[] = { "

/-- The swap `post`: closes expected[], then the phases — u64le
builder into the pair, the call under test on the array's decayed
pointer, u64le readback of both post-state cells, mismatch-index
comparator. -/
def swapBody : String :=
" };
  unsigned long int pair[2];
  unsigned char out[16];
  unsigned long i, j, acc;
  /* phase 0 — stream validity (total on any splice): exactly the CN
     resource extent, two u64 cells */
  if (sizeof(choices) != 16u) { return 254; }
  /* phase 1 — builder: two u64le values from the choice stream */
  for (j = 0u; j < 2u; j++) {
    acc = 0ul;
    for (i = 0u; i < 8u; i++) {
      acc = acc + ((unsigned long)choices[8u*j + i] << (8u * i));
    }
    pair[j] = acc;
  }
  /* phase 2 — the call under test (the built array's own pointer) */
  swap_pair(pair);
  /* phase 3 — observation: both post-state cells, u64le;
     verdict — generic mismatch-index comparator (Form 1) */
  for (j = 0u; j < 2u; j++) {
    acc = pair[j];
    for (i = 0u; i < 8u; i++) {
      out[8u*j + i] = (unsigned char)(acc % 256u);
      acc = acc / 256u;
    }
  }
  if (sizeof(expected) != 16u) { return 255; }
  for (i = 0u; i < 16u; i++) {
    if (out[i] != expected[i]) { return (int)(1u + i); }
  }
  return 0;
}
"

/-- swap Form 1 (the production AND pinned-statement template),
healthy target. -/
def swapTemplate : HarnessTemplate where
  pre := header "swap_pair Form 1: u64 pair, mismatch-index"
    ++ swapTargetHealthy ++ preTail
  mid := seedMid
  post := swapBody

/-- swap Form 1, LOST-UPDATE PLANT target. -/
def swapPlantTemplate : HarnessTemplate where
  pre := header "swap_pair Form 1, LOST-UPDATE PLANT"
    ++ swapTargetPlant ++ preTail
  mid := seedMid
  post := swapBody

/-- The verbatim lookup target, with citation + CN spec (healthy).
The enum + the CN spec-function declaration ride along verbatim. -/
def lookupTargetHealthy : String :=
"/* TARGET — verbatim from deps/cn/tests/cn/cn_inline.c
   (rems-project/cn, BSD-2-Clause; clean-room source per the
   2026-08-22 corpus ruling; the file's f() and trusted main are
   replaced by this harness). CN annotations ride along as ordinary
   comments (arc-15 S0 probe (c)). */

enum size {
  big,
  medium,
  small,
};

/*@ function (i32) lookup_size_shift_cn (u32 sz) @*/

static inline int
lookup_size_shift (enum size sz)
/*@ cn_function lookup_size_shift_cn;
    ensures return == lookup_size_shift_cn(sz); @*/
{
  switch (sz) {
    case big:
      return 12;
    case medium:
      return 8;
    case small:
      return 2;
    default:
      /* shouldn't happen */
      return 0;
  }
}
"

/-- The lookup PLANT target: the WRONG-CONSTANT bug (`case medium:
returns big's 12` — the copy-paste bug), loudly marked. Blind on
every sz ≠ 1 (documented negative space; the lane demonstrates the
green twins). -/
def lookupTargetPlant : String :=
"/* TARGET — PLANT VARIANT (template-note §plant-test):
   lookup_size_shift is deliberately BROKEN (wrong constant: the
   medium arm returns big's 12). A healthy-looking verdict from this
   program at sz = 1 means the harness is vacuous. */

enum size {
  big,
  medium,
  small,
};

static inline int
lookup_size_shift (enum size sz)
{
  switch (sz) {
    case big:
      return 12;
    case medium:
      return 12; /* PLANT: wrong constant (should be 8) */
    case small:
      return 2;
    default:
      return 0;
  }
}
"

/-- The lookup `post`: closes expected[], then the phases — u32le
builder (rejecting sz ≥ 2^31, the int-build ceiling: 254), the call
under test through the enum conversion, i32le readback of the
result, mismatch-index comparator. -/
def lookupBody : String :=
" };
  unsigned char out[4];
  unsigned long i;
  long acc;
  int v, r;
  /* phase 0 — stream validity (total on any splice): u32le sz,
     int-representable (the enum argument's build ceiling) */
  if (sizeof(choices) != 4u) { return 254; }
  acc = 0L;
  for (i = 0u; i < 4u; i++) { acc = acc + ((long)choices[i] << (8u * i)); }
  if (acc >= 2147483648L) { return 254; }
  v = (int)acc;
  /* phase 2 — the call under test (int -> enum size conversion) */
  r = lookup_size_shift((enum size)v);
  /* phase 3 — observation: i32le(ret);
     verdict — generic mismatch-index comparator (Form 1) */
  acc = (long)r; if (acc < 0L) { acc = acc + 4294967296L; }
  for (i = 0u; i < 4u; i++) { out[i] = (unsigned char)(acc % 256L); acc = acc / 256L; }
  if (sizeof(expected) != 4u) { return 255; }
  for (i = 0u; i < 4u; i++) {
    if (out[i] != expected[i]) { return (int)(1u + i); }
  }
  return 0;
}
"

/-- lookup Form 1, healthy target. -/
def lookupTemplate : HarnessTemplate where
  pre := header "lookup_size_shift Form 1: enum scalar, mismatch-index"
    ++ lookupTargetHealthy ++ preTail
  mid := seedMid
  post := lookupBody

/-- lookup Form 1, WRONG-CONSTANT PLANT target. -/
def lookupPlantTemplate : HarnessTemplate where
  pre := header "lookup_size_shift Form 1, WRONG-CONSTANT PLANT"
    ++ lookupTargetPlant ++ preTail
  mid := seedMid
  post := lookupBody

/-! ## Rendered-harness constructors (expected[] always the PURE
    model image — computed at statement-construction time) -/

/-- swap harness for a model pair (full domain — no Wf argument). -/
def mkSwap (m : PairInput) : String :=
  mkHarness swapTemplate (encodePair m) (expectedBytes m)

/-- swap harness for a RAW stream (fuzz entry — malformed splices are
DEFINED programs returning 254, with the junk expected splice). -/
def mkSwapOfStream (s : Stream) : String :=
  mkHarness swapTemplate s (expectedOfStream s)

def mkSwapPlant (m : PairInput) : String :=
  mkHarness swapPlantTemplate (encodePair m) (expectedBytes m)

/-- lookup harness for a well-formed sz. -/
def mkLookup (sz : Int) : String :=
  mkHarness lookupTemplate (encodeSz sz) (lookupExpected sz)

/-- lookup harness for a RAW stream (malformed/over-ceiling splices
return 254). -/
def mkLookupOfStream (s : Stream) : String :=
  mkHarness lookupTemplate s
    (match Codec.decodeU32LE s with
     | some (u, []) =>
       if u.toNat < 2147483648 then lookupExpected (u.toNat : Int)
       else junkExpected
     | _ => junkExpected)

def mkLookupPlant (sz : Int) : String :=
  mkHarness lookupPlantTemplate (encodeSz sz) (lookupExpected sz)

end CnSeed
end SpecLab
