/-
SpecLab.MkHarness — the harness source splicer, v1 (arc-15 S0).

Mechanism A of the harness statement template
(notes/2026-08-22_harness-statement-template.md, [USER 2026-08-22]
ratified): `mkHarness` splices two byte-array literals — `choices[]`
(the resolved choice stream) and `expected[]` (the pure-side-computed
expected observation) — into a FIXED C template. Every instance is a
closed, deterministic, concrete C program: oracle-runnable
bit-for-bit, fuzzable by sampling streams, replayable as its own
source text. The theorem quantifies over the program FAMILY.

THIS IS THE SINGLE TRUST POINT of the whole template (template note,
"the single trust point"): both pipelines consume the SAME rendered
text, so there is no reasoned-about/ran gap — but the splice itself
must be obviously faithful. Design rules, obvious over clever:

  * A template is THREE LITERAL STRING PARTS (`pre`/`mid`/`post`);
    rendering is four-way concatenation with the two rendered byte
    arrays in between. No searching, no replacement, no escaping —
    nothing that could silently misfire.
  * `renderByteArrayLiteral` renders each byte as its decimal Nat
    (0-255), comma-separated — the only value-to-text step. Its
    faithfulness is exercised by an executable parse-back round trip
    in test/Unit/SpecLabTest.lean (a TEST, labeled as such; the
    statement-level guarantee comes from both pipelines consuming
    identical text, not from that test).

Attribution (idiom lineage): the three-phase harness shape (setup →
call under test → observation/verdict) is golean's harness ruling
(deps/golean docs/2026-08-12_example-spec-form.md §11, gallery
docs/verified-examples.md). Where golean parameterizes structures by
SCALAR harness arguments (input families, honestly weaker than
∀-data) and left its choice-consuming input pick DESIGNED, NOT BUILT,
this template builds the input channel as the compiled-in choice
stream — resolving choices BEFORE the program exists, which is what
keeps every instance deterministic and differentially testable. See
speclab/README.md for the full adopt/differ record.
-/

set_option autoImplicit false

namespace SpecLab

/-- A harness template: the fixed C text in three literal parts. The
rendered harness is `pre ++ <choices bytes> ++ mid ++ <expected bytes>
++ post` — `pre` ends just inside `choices[]`'s initializer braces,
`mid` carries everything between the two initializers, `post` is the
whole remainder (builder, call under test, observation, comparator,
teardown). -/
structure HarnessTemplate where
  pre : String
  mid : String
  post : String
  deriving Repr

/-- Render a byte list as the inside of a C `unsigned char[]`
initializer: decimal, comma-separated (`renderByteArrayLiteral [3,
255] = "3, 255"`). NOTE: an EMPTY list renders as the empty string,
producing `{ }` — invalid C before C23; v1 templates keep both arrays
nonempty (the codecs' length prefixes guarantee this for any encoded
value). -/
def renderByteArrayLiteral (bs : List UInt8) : String :=
  String.intercalate ", " (bs.map (fun b => toString b.toNat))

/-- The splice: the single trust point. Four-way concatenation —
nothing else. -/
def mkHarness (t : HarnessTemplate) (choices expected : List UInt8) :
    String :=
  t.pre ++ renderByteArrayLiteral choices
        ++ t.mid ++ renderByteArrayLiteral expected ++ t.post

/-- The v1 reference template: the IDENTITY harness. Builder =
byte-blaster (copies `choices` verbatim into a buffer — the
containment-note byte-level builder in its smallest form), call under
test = identity, observation = the generic mismatch-index comparator
(template note Form 1: returns `0` on agreement, `1 + i` at the first
diverging position, `255` on length divergence — never a bare
boolean, so vacuity is loud). nolibc-clean: no includes, no libc
calls. S1 splices real subjects; this template exists so the S0
plant-test runner has a live end-to-end instance. -/
def identityTemplateV1 : HarnessTemplate where
  pre := "/* SpecLab identity harness v1 (mechanism A). Generated by
   SpecLab.mkHarness — do not edit by hand.
   Idiom lineage: golean three-phase harness (setup - call - test);
   see lean_frontend/speclab/README.md. */

static const unsigned char choices[] = { "
  mid := " };

static const unsigned char expected[] = { "
  post := " };

int main(void)
{
  unsigned char buf[sizeof(choices)];
  unsigned long i;
  /* phase 1 — builder: byte-blaster (verbatim copy) */
  for (i = 0; i < sizeof(choices); i++) {
    buf[i] = choices[i];
  }
  /* phase 2 — call under test: identity (v1 scaffold) */
  /* phase 3 — observation: generic mismatch-index comparator.
     0 = agreement; 1 + i = first divergence at position i;
     255 = length divergence. */
  if (sizeof(buf) != sizeof(expected)) {
    return 255;
  }
  for (i = 0; i < sizeof(expected); i++) {
    if (buf[i] != expected[i]) {
      return (int)(1 + i);
    }
  }
  return 0;
}
"

/-- Render the identity harness for a choice stream: `expected` is the
pure model image of `choices` — for the identity subject, `choices`
itself. The theorem shape this instantiates (S1 onward):
`∀ m, exec (mkHarness t (encode m) (encodeResult (modelFn m))) ⇓
Specified 0`. -/
def mkIdentityHarness (choices : List UInt8) : String :=
  mkHarness identityTemplateV1 choices choices

end SpecLab
