#!/usr/bin/env python3
"""gen_fuel_parametricity.py — the fuel-parametricity pin list of
lean_frontend/test/Unit/TotalityProofTest.lean Part 1, derived from the
generated tree (fuel-parameter arc C1; pre-merge audit M1: the list must not
be a static snapshot with an uncommitted generator).

For every AMBIENT fuel wrapper in lean_frontend/generated/ — a line
`def f <binders> [LemFuel] : T := f_lemFuel LemFuel.fuel` in a generated
(non-seam) module — emit `example <binders> (n : Nat) : @f <args> ⟨n⟩ =
@f_lemFuel <args> [⟨n⟩] n := rfl`, `⟨n⟩ n` on the right when the worker
itself carries `[LemFuel]` (it passes the ambient on). Binders are read from
the generated heads, so a drift in a wrapper's binders fails the test's
build; THIS script's --check makes a drift in the wrapper SET fail
test_unit.sh: the set of wrapper names in the tree must equal the set pinned
in TotalityProofTest.lean, both directions (a new fuel'd function without a
pin, or a pin whose function is gone, is RED). Measured wrappers
(`f_lemFuel (t.lemSize x) …`) are not ambient and are not listed — their
fuel-freedom is pinned by their sufficiency obligations instead.

Usage:
  gen_fuel_parametricity.py --emit    print the Part 1 block (paste into the test)
  gen_fuel_parametricity.py --check   compare the tree's wrapper set with the test's pins; exit 1 on drift
"""
import re, sys, os, glob

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
LF = os.path.join(ROOT, 'lean_frontend')
TEST = os.path.join(LF, 'test', 'Unit', 'TotalityProofTest.lean')

def seam_names():
    with open(os.path.join(LF, 'handwritten_copy.manifest')) as fh:
        return {l.strip() for l in fh if l.strip() and not l.startswith('#')}

def wrappers():
    """(module, name, wrapper-binders, worker-carries-fuel) for every ambient wrapper."""
    rows = []
    seams = seam_names()
    for f in sorted(glob.glob(os.path.join(LF, 'generated', '*.lean'))):
        b = os.path.basename(f)
        if b in seams:
            continue
        t = open(f).read()
        for m in re.finditer(r'^def\s+(\w+)\s+((?:\{[^}]*\}\s*|\[[^\]]*\]\s*)*):\s*(.*?)\s*:=\s*(\w+)_lemFuel LemFuel\.fuel\s*$', t, re.M):
            name, binders = m.group(1), m.group(2)
            if m.group(4) != name:
                sys.exit(f"gen_fuel_parametricity: {b}: wrapper {name} applies {m.group(4)}_lemFuel — unexpected shape")
            w = re.search(r'^\s*def\s+' + re.escape(name) + r'_lemFuel\s+(.*?)\(lemFuel : Nat\)', t, re.M)
            if not w:
                sys.exit(f"gen_fuel_parametricity: {b}: no worker head for {name}")
            rows.append((b[:-5], name, binders, '[LemFuel]' in w.group(1)))
    if len(rows) < 10:
        sys.exit(f"gen_fuel_parametricity: only {len(rows)} wrappers found — is lean_frontend/generated regenerated? (vacuity guard)")
    return rows

def parse_binders(bs):
    out = []
    for m in re.finditer(r'\{([^}]*)\}|\[([^\]]*)\]', bs):
        if m.group(1) is not None:
            names, ty = m.group(1).split(':')
            out.append(('impl', [x for x in names.split() if x], ty.strip()))
        else:
            out.append(('inst', m.group(2).strip()))
    return out

def emit(rows):
    lines = [f"-- {len(rows)} ambient wrappers (generated by scripts/gen_fuel_parametricity.py --emit from the generated tree; scripts/gen_fuel_parametricity.py --check pins this SET in test_unit.sh)"]
    for mod, name, wb, worker_fuel in rows:
        parsed = parse_binders(wb)
        tys = [n for k, ns, _ in [(x[0], x[1], x[2]) if x[0] == 'impl' else (x[0], [], None) for x in parsed] if k == 'impl' for n in ns]
        insts = [x[1] for x in parsed if x[0] == 'inst' and x[1] != 'LemFuel']
        btxt = ''
        if tys:
            btxt += ' {' + ' '.join(tys) + ' : Type}'
        instnames = []
        for i, c in enumerate(insts):
            nm = f'i{i+1}'; instnames.append(nm); btxt += f' [{nm} : {c}]'
        args = ' '.join(tys + instnames)
        lhs = f'@{name}' + (' ' + args if args else '') + ' ⟨n⟩'
        rhs = f'@{name}_lemFuel' + (' ' + args if args else '') + (' ⟨n⟩ n' if worker_fuel else ' n')
        lines.append(f'example{btxt} (n : Nat) : {lhs} = {rhs} := rfl')
    return '\n'.join(lines)

def pinned():
    t = open(TEST).read()
    return set(re.findall(r'^example.*?:\s*@(\w+)(?:\s+[^⟨]*)?⟨n⟩\s*=\s*@\1_lemFuel\b', t, re.M))

def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else ''
    rows = wrappers()
    if mode == '--emit':
        print(emit(rows)); return
    if mode == '--check':
        tree = {r[1] for r in rows}
        pins = pinned()
        missing = sorted(tree - pins); stale = sorted(pins - tree)
        if missing or stale:
            if missing:
                print("gen_fuel_parametricity: FAIL — fuel'd wrapper(s) in the tree with NO parametricity pin in TotalityProofTest.lean: " + ', '.join(missing))
            if stale:
                print("gen_fuel_parametricity: FAIL — pin(s) in TotalityProofTest.lean with no wrapper in the tree: " + ', '.join(stale))
            print("  regenerate Part 1: scripts/gen_fuel_parametricity.py --emit")
            sys.exit(1)
        print(f"gen_fuel_parametricity: OK ({len(tree)} ambient fuel wrappers in the generated tree = the {len(pins)} pins of TotalityProofTest.lean Part 1, both directions)")
        return
    sys.exit(__doc__)

if __name__ == '__main__':
    main()
