#!/usr/bin/env python3
"""Build the declaration-dependency instrument against a cold provider build."""
import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys

from build_independent_oracle import files, sha

ROOT = Path(__file__).resolve().parent.parent


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--provider-manifest', type=Path, required=True)
    parser.add_argument('--out', type=Path, required=True)
    args = parser.parse_args()
    provider = args.provider_manifest.resolve().parent
    manifest = json.loads(args.provider_manifest.read_text())
    cerb = provider/'cerberus'
    if manifest['status'] != 'passed' or files(cerb/'lean_frontend/generated') != manifest['generated_lean']:
        raise SystemExit('provider rehearsal incomplete or generated bytes changed')
    out = args.out.resolve()
    out.mkdir(parents=True, exist_ok=False)
    shutil.copy2(ROOT/'tests/failure-probes/FailureReach.lean', out/'FailureReach.lean')
    shutil.copy2(cerb/'lean_frontend/lean-toolchain', out/'lean-toolchain')
    (out/'lakefile.toml').write_text('name = "FailureCensus"\ndefaultTargets = ["FailureReach"]\n'
        f'packagesDir = {json.dumps(str(cerb/"lean_frontend/.lake/packages"))}\n'
        '[[require]]\nname = "CerberusLean"\n'
        f'path = {json.dumps(str(cerb/"lean_frontend"))}\n[[lean_lib]]\nname = "FailureReach"\n')
    command = [str(ROOT/'scripts/capped'), 'lake', 'build']
    with (out/'reach.log').open('wb') as log:
        proc = subprocess.run(command, cwd=out, env=dict(os.environ, CERB_MEM_MAX='32G'),
                              stdout=log, stderr=subprocess.STDOUT, timeout=120)
    meta = {'schema': 1, 'provider_manifest_sha256': sha(args.provider_manifest),
            'instrument_sha256': sha(out/'FailureReach.lean'), 'command': command,
            'exit_status': proc.returncode, 'log_sha256': sha(out/'reach.log')}
    (out/'instrument.json').write_text(json.dumps(meta, indent=2)+'\n')
    if proc.returncode:
        raise SystemExit('dependency instrument failed; see reach.log')
    return subprocess.run([sys.executable, str(ROOT/'scripts/failure_census.py'), '--root', str(cerb),
        '--reach-log', str(out/'reach.log'), '--out', str(out/'census.json')]).returncode


if __name__ == '__main__': sys.exit(main())
