#!/usr/bin/env python3
"""Byte-preserving Cabs bridge probe (semantics-audit repairs D2, 2026-09-11).

Called by test_parse.sh after test_batch_diagnostics.py. Exercises the REAL
`--cabs-json` exporter and the real Lean importer on a C string literal whose
fragments are every raw source byte 0x80..0xFF in order, and asserts the
project's byte-carrier convention across the bridge (record
lean_frontend/docs/2026-09-11_semantics-audit-repairs-record.md §D2;
convention: lean_frontend/docs/2026-09-09_batch-diagnostic-bytes-record.md):

  1. the exporter exits 0 and its JSON is VALID UTF-8 (strict decode);
  2. the CabsEstring fragments in that JSON are 128 one-character strings
     whose code points are exactly the bytes 0x80..0xFF, in order
     (cabs_json.ml json_of_bytes: one JSON code point U+00XX per byte);
  3. the Lean driver's `--batch` verdict on that JSON is
     `Defined {value: "Specified(129)", …}` (sizeof = fragments + 1; the bytes
     are counted, never decoded — decode.ml:199-200 / CerbDecode would
     fail-stop on a decoded raw high byte, which is the oracle's class).

Fail-closed: any deviation is a nonzero exit naming the failed step. Before
D2 the exporter wrote the raw bytes (`json_of_string`), the JSON was not
UTF-8 and Lean refused the file — step 1 goes RED on that exporter (the
plant recorded in the D2 record was the pre-D2 binary itself).
"""
import argparse
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RUNTIME = ROOT / '_build/install/default'
EXPECTED_VERDICT = b'Defined {value: "Specified(129)", stdout: "", stderr: "", blocked: "false"}\n'


def fail(step, msg):
    print(f'cabs bytes probe: FAIL at step {step}: {msg}', file=sys.stderr)
    sys.exit(1)


def find_string_literals(node, out):
    """Collect every CabsEstring value in the tagged JSON tree."""
    if isinstance(node, dict):
        if node.get('tag') == 'CabsEstring' and 'val' in node:
            out.append(node['val'])
        for v in node.values():
            find_string_literals(v, out)
    elif isinstance(node, list):
        for v in node:
            find_string_literals(v, out)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--oracle-bin', required=True, type=Path)
    ap.add_argument('--lean-bin', required=True, type=Path)
    args = ap.parse_args()
    oracle = args.oracle_bin.resolve()
    lean = args.lean_bin.resolve()
    for b in (oracle, lean):
        if not b.is_file():
            fail(0, f'binary missing: {b}')
    high = bytes(range(0x80, 0x100))
    program = (b'/* generated by scripts/test_cabs_bytes_probe.py: the literal holds every raw byte'
               b' 0x80..0xFF in order (128 bytes); sizeof counts them + NUL = 129 */\n'
               b'int main(void) { return sizeof("' + high + b'"); }\n')
    env = {**os.environ, 'LC_ALL': 'C', 'NO_COLOR': '1', 'TERM': 'dumb', 'LEAN_ABORT_ON_PANIC': '1'}
    with tempfile.TemporaryDirectory(prefix='cabs_bytes_probe.') as td:
        c_path = Path(td) / 'raw_high_bytes.c'
        c_path.write_bytes(program)
        # Step 1: the real exporter; its output must be valid UTF-8.
        r = subprocess.run([str(oracle), f'--runtime={RUNTIME}', '--nolibc', '--cabs-json', str(c_path)],
                           capture_output=True, timeout=60, cwd=ROOT, env=env)
        if r.returncode != 0:
            fail(1, f'--cabs-json exit {r.returncode}: {r.stderr[-400:]!r}')
        try:
            text = r.stdout.decode('utf-8', errors='strict')
        except UnicodeDecodeError as e:
            fail(1, f'--cabs-json output is NOT valid UTF-8: {e} (raw-byte write reintroduced?)')
        # Step 2: the fragments are the bytes, one code point each, in order.
        try:
            tree = json.loads(text)
        except json.JSONDecodeError as e:
            fail(2, f'--cabs-json output is not JSON: {e}')
        lits = []
        find_string_literals(tree, lits)
        if len(lits) != 1:
            fail(2, f'expected exactly 1 CabsEstring, found {len(lits)}')
        enc, parts = lits[0]
        if enc is not None or len(parts) != 1:
            fail(2, f'unexpected literal shape: enc={enc!r} parts={len(parts)}')
        frags = parts[0][1]
        got = [ord(s) if len(s) == 1 else None for s in frags]
        want = list(range(0x80, 0x100))
        if got != want:
            head = frags[:4]
            fail(2, f'fragment code points != bytes 0x80..0xFF: {len(frags)} fragments, first {head!r}, '
                    f'first mismatch at index {next((i for i, (g, w) in enumerate(zip(got, want)) if g != w), len(want))}')
        # Step 3: the imported literal is counted by the Lean pipeline as 129 bytes.
        json_path = Path(td) / 'raw_high_bytes.json'
        json_path.write_bytes(r.stdout)
        rl = subprocess.run([str(ROOT / 'scripts/capped'), str(lean), '--batch', str(json_path)],
                            capture_output=True, timeout=120, cwd=ROOT, env=env)
        if rl.returncode != 0 or rl.stdout != EXPECTED_VERDICT:
            fail(3, f'Lean --batch exit {rl.returncode}, stdout {rl.stdout!r}, stderr {rl.stderr[-400:]!r}; '
                    f'expected {EXPECTED_VERDICT!r}')
    print('cabs bytes probe: 128 raw bytes 0x80..0xFF crossed the bridge as one code point each '
          '(valid UTF-8 JSON; Lean sizeof = 129)')


if __name__ == '__main__':
    main()
