import SpecLab
open SpecLab
#print axioms Codec.decode_encode_u8
#print axioms Codec.decode_encode_u16le
#print axioms Codec.decode_encode_u32le
#print axioms Codec.decode_encode_u64le
#print axioms Codec.decodeElems_encodeElems
#print axioms Codec.decode_encode_arrayU16
#print axioms DivMod.ofU32_toU32
#print axioms DivMod.toU32_ofU32
#print axioms DivMod.decode_encode_i32le
#print axioms DivMod.encode_decode_u16le
#print axioms DivMod.encode_decode_u32le
#print axioms DivMod.encode_decode_i32le'
#print axioms DivMod.decode_encode_input
#print axioms DivMod.encode_decode_input
#print axioms DivMod.model_forall_iff_stream_forall
#print axioms DivMod.divmod_reconstruction
#print axioms DivMod.modelMod_bound
#print axioms DivMod.modelDiv_inRange
#print axioms DivMod.modelMod_inRange
#print axioms DivMod.ofByteI8_toByteI8
#print axioms DivMod.decode_encode_inputI8
#print axioms DivMod.fileOfStream_encode
#print axioms DivMod.sample_model_iff_stream
#print axioms DivMod.divmodI8File
#print axioms DivMod.divmodI8PlantFile
#print axioms DivMod.divmodI8FileOf
#print axioms DivMod.DivModI8SampleStatement
#print axioms DivMod.DivModI8SampleStreamStatement
#print axioms DivMod.DivModI8PlantHealthyClaim
#print axioms SpecLab.DivModCore.mainParamDecl
#print axioms SpecLab.DivModCore.divisionDecl
